version: '3'

networks:
  next-enrollment-app:


services:
  app:
    # build:
    #   context: ./dockerfiles
    #   dockerfile: nginx.dockerfile
    #   args:
    #     - UID=${UID:-1000}
    #     - GID=${GID:-1000}
    # ports:
    #   - "80:80"
    # volumes:
    #   - ./src:/var/www/html:delegated
    # depends_on:
    #   - php
    #   - redis
    #   - mysql
    #   - mailhog
    # networks:
    #   - next-enrollment-app

  # mysql:
  #   image: mariadb:10.6
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - next-enrollment-app

  # php:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: php.dockerfile
  #     args:
  #       - UID=${UID:-1000}
  #       - GID=${GID:-1000}
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./src:/var/www/html:delegated
  #   networks:
  #     - next-enrollment-app

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - next-enrollment-app

  # composer:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: php.dockerfile
  #     args:
  #       - UID=${UID:-1000}
  #       - GID=${GID:-1000}
  #   volumes:
  #     - ./src:/var/www/html
  #   depends_on:
  #     - php
  #   entrypoint: [ 'composer', '--ignore-platform-reqs' ]
  #   networks:
  #     - next-enrollment-app

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - next-enrollment-app

  # artisan:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: php.dockerfile
  #     args:
  #       - UID=${UID:-1000}
  #       - GID=${GID:-1000}
  #   volumes:
  #     - ./src:/var/www/html:delegated
  #   depends_on:
  #     - mysql
  #   entrypoint: [ 'php', '/var/www/html/artisan' ]
  #   networks:
  #     - next-enrollment-app

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - next-enrollment-app